[project]
name = "maskface"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "librosa>=0.11.0",
    "moviepy>=2.2.1",
    "numpy>=2.4.6",
    "opencv-python>=4.10,<5",
    "sv-ttk>=2.6.1",
    "tqdm>=4.70.0",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.22.2",
]
